"""Schema vocabulary shared by independently authored content concepts."""

from .base import Ability, CapabilitySchemaModel, NonNegativeInt, PositiveInt
from .durations import EffectDurationSchema, TimedDurationSchema
from .effects import (
    ActionEffectSchema,
    AttackHitDamageEffectSchema,
    AttackHitRetaliationEffectSchema,
    CompelledTurnEffectSchema,
    ConditionEffectSchema,
    ControlEffectSchema,
    DamageEffectSchema,
    DestructibleConditionSchema,
    ForcedMovementEffectSchema,
    GainMemoriesEffectSchema,
    HitPointMaximumReductionEffectSchema,
    ProhibitReactionEffectSchema,
    RollModifierEffectSchema,
    SpeedMultiplierEffectSchema,
    TeleportEffectSchema,
    TurnEconomyRestrictionEffectSchema,
)
from .errors import CapabilityBuildError
from .requirements import (
    ActionRequirementSchema,
    ConditionRequirementSchema,
    CreatureTypeRequirementSchema,
    NotAffectedRequirementSchema,
    SizeRequirementSchema,
)
from .resolutions import (
    AutomaticResolutionSchema,
    DerivedDifficultyClassSchema,
    DifficultyClassSchema,
    FixedDifficultyClassSchema,
    OutcomeSchema,
    ResolutionSchemaModel,
    SavingThrowResolutionSchema,
)
from .targets import (
    ActionTargetSchema,
    AreaTargetSchema,
    CreatureTargetSchema,
    SelfTargetSchema,
)

__all__ = [
    "Ability",
    "ActionEffectSchema",
    "ActionRequirementSchema",
    "ActionTargetSchema",
    "AreaTargetSchema",
    "AttackHitDamageEffectSchema",
    "AttackHitRetaliationEffectSchema",
    "AutomaticResolutionSchema",
    "CapabilityBuildError",
    "CapabilitySchemaModel",
    "CompelledTurnEffectSchema",
    "ConditionEffectSchema",
    "ConditionRequirementSchema",
    "ControlEffectSchema",
    "CreatureTargetSchema",
    "CreatureTypeRequirementSchema",
    "DamageEffectSchema",
    "DerivedDifficultyClassSchema",
    "DestructibleConditionSchema",
    "DifficultyClassSchema",
    "EffectDurationSchema",
    "FixedDifficultyClassSchema",
    "ForcedMovementEffectSchema",
    "GainMemoriesEffectSchema",
    "HitPointMaximumReductionEffectSchema",
    "NonNegativeInt",
    "NotAffectedRequirementSchema",
    "OutcomeSchema",
    "PositiveInt",
    "ProhibitReactionEffectSchema",
    "ResolutionSchemaModel",
    "RollModifierEffectSchema",
    "SavingThrowResolutionSchema",
    "SelfTargetSchema",
    "SizeRequirementSchema",
    "SpeedMultiplierEffectSchema",
    "TeleportEffectSchema",
    "TimedDurationSchema",
    "TurnEconomyRestrictionEffectSchema",
]
