"""Schema vocabulary shared by independently authored content concepts."""

from .base import Ability, CapabilitySchemaModel, NonNegativeInt, PositiveInt
from .durations import EffectDurationSchema, TimedDurationSchema
from .errors import CapabilityBuildError
from .effects import (
    ActionEffectSchema,
    ArmorClassModifierEffectSchema,
    ConditionEffectSchema,
    ConditionImmunityEffectSchema,
    ConditionSaveAdvantageEffectSchema,
    ControlEffectSchema,
    DamageEffectSchema,
    DamageImmunityEffectSchema,
    DamageReductionEffectSchema,
    DamageResistanceEffectSchema,
    ForcedMovementEffectSchema,
    GainMemoriesEffectSchema,
    HealingEffectSchema,
    HitPointMaximumModifierEffectSchema,
    ProhibitReactionEffectSchema,
    RemoveEffectSchema,
    RollModifierEffectSchema,
    SenseEffectSchema,
    SpeedModifierEffectSchema,
    SpeedMultiplierEffectSchema,
    TemporaryHitPointsEffectSchema,
    TurnEconomyRestrictionEffectSchema,
)
from .requirements import (
    ActionRequirementSchema,
    ConditionImmunityRequirementSchema,
    ConditionRequirementSchema,
    CreatureTraitRequirementSchema,
    CreatureTypeRequirementSchema,
    NotAffectedRequirementSchema,
    RelationshipRequirementSchema,
    SizeRequirementSchema,
)
from .targets import (
    ActionTargetSchema,
    AreaTargetSchema,
    CreatureTargetSchema,
    SelfTargetSchema,
)
from .resolutions import (
    AutomaticResolutionSchema,
    DerivedDifficultyClassSchema,
    DifficultyClassSchema,
    FixedDifficultyClassSchema,
    OutcomeSchema,
    ResolutionSchemaModel,
    SavingThrowResolutionSchema,
)

__all__ = [
    "Ability",
    "AutomaticResolutionSchema",
    "ActionEffectSchema",
    "CapabilitySchemaModel",
    "CapabilityBuildError",
    "ActionRequirementSchema",
    "ActionTargetSchema",
    "AreaTargetSchema",
    "ArmorClassModifierEffectSchema",
    "ConditionEffectSchema",
    "ConditionImmunityEffectSchema",
    "ConditionImmunityRequirementSchema",
    "ConditionRequirementSchema",
    "ConditionSaveAdvantageEffectSchema",
    "ControlEffectSchema",
    "CreatureTargetSchema",
    "CreatureTraitRequirementSchema",
    "CreatureTypeRequirementSchema",
    "DamageEffectSchema",
    "DamageImmunityEffectSchema",
    "DamageReductionEffectSchema",
    "DamageResistanceEffectSchema",
    "DerivedDifficultyClassSchema",
    "DifficultyClassSchema",
    "EffectDurationSchema",
    "ForcedMovementEffectSchema",
    "FixedDifficultyClassSchema",
    "GainMemoriesEffectSchema",
    "HealingEffectSchema",
    "HitPointMaximumModifierEffectSchema",
    "NonNegativeInt",
    "NotAffectedRequirementSchema",
    "OutcomeSchema",
    "PositiveInt",
    "ProhibitReactionEffectSchema",
    "RemoveEffectSchema",
    "RelationshipRequirementSchema",
    "RollModifierEffectSchema",
    "ResolutionSchemaModel",
    "SavingThrowResolutionSchema",
    "SenseEffectSchema",
    "SelfTargetSchema",
    "SizeRequirementSchema",
    "SpeedModifierEffectSchema",
    "SpeedMultiplierEffectSchema",
    "TemporaryHitPointsEffectSchema",
    "TimedDurationSchema",
    "TurnEconomyRestrictionEffectSchema",
]
