"""Schema vocabulary shared by independently authored content concepts."""

from .schemas.base import Ability, CapabilitySchemaModel, NonNegativeInt, PositiveInt
from .schemas.authoring.resolutions import (
    CapabilityEffectSchema,
    CapabilityResolutionSchema,
)
from .schemas.authoring.declarations import (
    CapabilityDeclarationSchema,
)
from .schemas.durations import EffectDurationSchema, TimedDurationSchema
from .building import CapabilityBuildError, build_capability
from .schemas.definitions import CapabilitySchemaBase, OutcomeTriggerSchemaBase
from .schemas.effects import (
    ActionEffectSchema,
    ExecutableEffectSchema,
    ArmorClassModifierEffectSchema,
    ConditionEffectSchema,
    ConditionImmunityEffectSchema,
    ConditionSaveAdvantageEffectSchema,
    DamageEffectSchema,
    DamageReductionEffectSchema,
    DamageResistanceEffectSchema,
    HealingEffectSchema,
    HitPointMaximumModifierEffectSchema,
    RemoveEffectSchema,
    RollModifierEffectSchema,
    SenseEffectSchema,
    SpeedModifierEffectSchema,
    TemporaryHitPointsEffectSchema,
)
from .schemas.requirements import (
    AllRequirementSchema,
    AnyRequirementSchema,
    AttackSourceRequirementSchema,
    CapabilityRequirementSchema,
    ConditionImmunityRequirementSchema,
    ConditionRequirementSchema,
    CreatureTraitRequirementSchema,
    CreatureTypeRequirementSchema,
    FreeHandRequirementSchema,
    HitPointRequirementSchema,
    NotAffectedRequirementSchema,
    PerceptionRequirementSchema,
    RelationshipRequirementSchema,
    SizeRequirementSchema,
    WillingRequirementSchema,
)
from .schemas.targets import (
    ActionAreaTargetSchema,
    ActionCreatureTargetSchema,
    ActionTargetSchema,
    AreaGeometrySchema,
    AreaTargetSchema,
    CreatureTargetSchema,
    ExecutableTargetSchema,
    SelfTargetSchema,
    TargetCountSchema,
)
from .schemas.resolutions import (
    AttackResolutionSchema,
    AutomaticResolutionSchema,
    DerivedDifficultyClassSchema,
    DifficultyClassSchema,
    FixedDifficultyClassSchema,
    FixedAttackResolutionSchema,
    OutcomeSchema,
    RepeatResolutionSchemaBase,
    RepeatSaveProgressionSchemaBase,
    ResolutionSchemaModel,
    SavingThrowResolutionSchema,
    SavingThrowModifierSchema,
    SequenceResolutionSchemaBase,
)
from .schemas.scaling import (
    ActorLevelScalingSchema,
    ActorLevelScalingThresholdSchema,
    CapabilityScalingSchema,
    ResourceScalingSchema,
    ScalingIncrementSchema,
)
from .building.supported import (
    EXECUTABLE_EFFECT_TYPES,
    EXECUTABLE_REQUIREMENT_TYPES,
    EXECUTABLE_RESOLUTION_TYPES,
    EXECUTABLE_TARGET_TYPES,
)

__all__ = [
    "Ability",
    "ActorLevelScalingSchema",
    "ActorLevelScalingThresholdSchema",
    "AutomaticResolutionSchema",
    "ActionEffectSchema",
    "ExecutableEffectSchema",
    "ActionAreaTargetSchema",
    "ActionCreatureTargetSchema",
    "CapabilitySchemaModel",
    "CapabilitySchemaBase",
    "CapabilityScalingSchema",
    "build_capability",
    "CapabilityBuildError",
    "AllRequirementSchema",
    "AnyRequirementSchema",
    "AttackSourceRequirementSchema",
    "CapabilityRequirementSchema",
    "CapabilityDeclarationSchema",
    "CapabilityEffectSchema",
    "CapabilityResolutionSchema",
    "FreeHandRequirementSchema",
    "HitPointRequirementSchema",
    "PerceptionRequirementSchema",
    "WillingRequirementSchema",
    "ActionTargetSchema",
    "AreaTargetSchema",
    "AreaGeometrySchema",
    "AttackResolutionSchema",
    "ArmorClassModifierEffectSchema",
    "ConditionEffectSchema",
    "ConditionImmunityEffectSchema",
    "ConditionImmunityRequirementSchema",
    "ConditionRequirementSchema",
    "ConditionSaveAdvantageEffectSchema",
    "CreatureTargetSchema",
    "CreatureTraitRequirementSchema",
    "CreatureTypeRequirementSchema",
    "DamageEffectSchema",
    "DamageReductionEffectSchema",
    "DamageResistanceEffectSchema",
    "DerivedDifficultyClassSchema",
    "DifficultyClassSchema",
    "EffectDurationSchema",
    "EXECUTABLE_EFFECT_TYPES",
    "EXECUTABLE_REQUIREMENT_TYPES",
    "EXECUTABLE_RESOLUTION_TYPES",
    "EXECUTABLE_TARGET_TYPES",
    "ExecutableTargetSchema",
    "FixedDifficultyClassSchema",
    "FixedAttackResolutionSchema",
    "HealingEffectSchema",
    "HitPointMaximumModifierEffectSchema",
    "NonNegativeInt",
    "NotAffectedRequirementSchema",
    "OutcomeSchema",
    "OutcomeTriggerSchemaBase",
    "PositiveInt",
    "RemoveEffectSchema",
    "RepeatResolutionSchemaBase",
    "RepeatSaveProgressionSchemaBase",
    "RelationshipRequirementSchema",
    "ResourceScalingSchema",
    "RollModifierEffectSchema",
    "ResolutionSchemaModel",
    "SavingThrowResolutionSchema",
    "SavingThrowModifierSchema",
    "ScalingIncrementSchema",
    "SenseEffectSchema",
    "SequenceResolutionSchemaBase",
    "SelfTargetSchema",
    "SizeRequirementSchema",
    "SpeedModifierEffectSchema",
    "TemporaryHitPointsEffectSchema",
    "TimedDurationSchema",
    "TargetCountSchema",
]
