"""Stable in-process API for driving SRD Arena engine sessions.

Driving adapters should import commands, observations, and the session from
this module. Implementation modules remain free to change without becoming
accidental frontend dependencies.
"""

from .area_coverage import area_aims
from .area_observation_models import AreaAimObservation, AreaTemplateObservation
from .commands import (
    AimAction,
    CastSpell,
    CommandFailure,
    CommandResult,
    GameCommand,
    GameEvent,
    GameUpdate,
    PlayerCommandResult,
    PlayerGameUpdate,
    SelectAction,
)
from .decision_state_observations import (
    ActionEconomyObservation,
    MovementBudgetObservation,
    ResourceObservation,
)
from .filtered_observations import (
    FILTERED_OBSERVATION_SCHEMA_ID,
    FilteredAction,
    FilteredCreature,
    FilteredObservation,
    PolicyProjector,
)
from .gameplay_observation_models import (
    GameplayConditionObservation,
    GameplayCreatureObservation,
    GameplayEffectObservation,
    GameplayEventObservation,
    GameplayObservation,
    GameplayTeamObservation,
)
from .movement_observations import MovementStepObservation
from .observation_policy import ObservationPolicy
from .observations import (
    ActionObservation,
    ActionReasonObservation,
    AttributeObservation,
    CreatureDefenseObservation,
    CreatureObservation,
    CreatureRelationshipObservation,
    DecisionObservation,
    EncounterCompletionObservation,
    EncounterObservation,
    EncounterTerminationReason,
    FeatureActionObservation,
    GameObservation,
    GridObservation,
    InitiativeObservation,
    InventoryItemObservation,
    OngoingEffectObservation,
    PositionObservation,
    ResourcePoolObservation,
    SceneObservation,
    SpellSlotObservation,
    TargetingObservation,
    TargetResourceAllocationObservation,
    TargetResourceLimitObservation,
)
from .player_observation_models import (
    PLAYER_OBSERVATION_SCHEMA_ID,
    AppearanceObservation,
    CreatureAllegiance,
    HealthBand,
    KnowledgeState,
    PlayerCreatureObservation,
    PlayerDecisionContext,
    PlayerObservation,
    PublicCombatEventObservation,
    PublicEventKind,
)
from .session import Session, SessionFactory
from .spell_capability_observations import SpellCapabilityObservation
from .spell_cast_observation_models import SpellCastOptions

__all__ = [
    "FILTERED_OBSERVATION_SCHEMA_ID",
    "PLAYER_OBSERVATION_SCHEMA_ID",
    "ActionEconomyObservation",
    "ActionObservation",
    "ActionReasonObservation",
    "AimAction",
    "AppearanceObservation",
    "AreaAimObservation",
    "AreaTemplateObservation",
    "AttributeObservation",
    "CastSpell",
    "CommandFailure",
    "CommandResult",
    "CreatureAllegiance",
    "CreatureDefenseObservation",
    "CreatureObservation",
    "CreatureRelationshipObservation",
    "DecisionObservation",
    "EncounterCompletionObservation",
    "EncounterObservation",
    "EncounterTerminationReason",
    "FeatureActionObservation",
    "FilteredAction",
    "FilteredCreature",
    "FilteredObservation",
    "GameCommand",
    "GameEvent",
    "GameObservation",
    "GameUpdate",
    "GameplayConditionObservation",
    "GameplayCreatureObservation",
    "GameplayEffectObservation",
    "GameplayEventObservation",
    "GameplayObservation",
    "GameplayTeamObservation",
    "GridObservation",
    "HealthBand",
    "InitiativeObservation",
    "InventoryItemObservation",
    "KnowledgeState",
    "MovementBudgetObservation",
    "MovementStepObservation",
    "ObservationPolicy",
    "OngoingEffectObservation",
    "PlayerCommandResult",
    "PlayerCreatureObservation",
    "PlayerDecisionContext",
    "PlayerGameUpdate",
    "PlayerObservation",
    "PolicyProjector",
    "PositionObservation",
    "PublicCombatEventObservation",
    "PublicEventKind",
    "ResourceObservation",
    "ResourcePoolObservation",
    "SceneObservation",
    "SelectAction",
    "Session",
    "SessionFactory",
    "SpellCapabilityObservation",
    "SpellCastOptions",
    "SpellSlotObservation",
    "TargetResourceAllocationObservation",
    "TargetResourceLimitObservation",
    "TargetingObservation",
    "area_aims",
]
