"""Stable in-process API for driving SRD Arena engine sessions.

Driving adapters should import commands, observations, and the session from
this module. Implementation modules remain free to change without becoming
accidental frontend dependencies.
"""

from .commands import (
    AimAction,
    CancelTargeting,
    ChangeTarget,
    CommandFailure,
    CommandResult,
    ConfirmTargeting,
    GameCommand,
    GameEvent,
    GameUpdate,
    PlayerCommandResult,
    PlayerGameUpdate,
    SelectAction,
    SetResourceAllocation,
)
from .observations import (
    ActionObservation,
    ActionReasonObservation,
    AttributeObservation,
    CreatureDefenseObservation,
    CreatureObservation,
    CreatureRelationshipObservation,
    DecisionObservation,
    EncounterCompletionObservation,
    EncounterObservation,
    EncounterTerminationReason,
    FeatureActionObservation,
    GameObservation,
    GridObservation,
    InitiativeObservation,
    InventoryItemObservation,
    OngoingEffectObservation,
    PositionObservation,
    ResourcePoolObservation,
    SceneObservation,
    SpellSlotObservation,
    TargetingObservation,
    TargetResourceAllocationObservation,
    TargetResourceLimitObservation,
)
from .player_observation_models import (
    PLAYER_OBSERVATION_SCHEMA_ID,
    AppearanceObservation,
    CreatureAllegiance,
    HealthBand,
    KnowledgeState,
    PlayerCreatureObservation,
    PlayerObservation,
    PublicCombatEventObservation,
    PublicEventKind,
)
from .session import Session, SessionFactory

__all__ = [
    "PLAYER_OBSERVATION_SCHEMA_ID",
    "ActionObservation",
    "ActionReasonObservation",
    "AimAction",
    "AppearanceObservation",
    "AttributeObservation",
    "CancelTargeting",
    "ChangeTarget",
    "CommandFailure",
    "CommandResult",
    "ConfirmTargeting",
    "CreatureAllegiance",
    "CreatureDefenseObservation",
    "CreatureObservation",
    "CreatureRelationshipObservation",
    "DecisionObservation",
    "EncounterCompletionObservation",
    "EncounterObservation",
    "EncounterTerminationReason",
    "FeatureActionObservation",
    "GameCommand",
    "GameEvent",
    "GameObservation",
    "GameUpdate",
    "GridObservation",
    "HealthBand",
    "InitiativeObservation",
    "InventoryItemObservation",
    "KnowledgeState",
    "OngoingEffectObservation",
    "PlayerCommandResult",
    "PlayerCreatureObservation",
    "PlayerGameUpdate",
    "PlayerObservation",
    "PositionObservation",
    "PublicCombatEventObservation",
    "PublicEventKind",
    "ResourcePoolObservation",
    "SceneObservation",
    "SelectAction",
    "Session",
    "SessionFactory",
    "SetResourceAllocation",
    "SpellSlotObservation",
    "TargetResourceAllocationObservation",
    "TargetResourceLimitObservation",
    "TargetingObservation",
]
