"""Schema vocabulary shared by independently authored content concepts."""

from .schema import (
    Ability,
    ActionEffectSchema,
    ActionMechanicsSchemaModel,
    ActionRequirementSchema,
    ActionTargetSchema,
    AreaTargetSchema,
    ConditionEffectSchema,
    ConditionRequirementSchema,
    ControlEffectSchema,
    CreatureTargetSchema,
    CreatureTypeRequirementSchema,
    DamageEffectSchema,
    EffectDurationSchema,
    ForcedMovementEffectSchema,
    GainMemoriesEffectSchema,
    NonNegativeInt,
    NotAffectedRequirementSchema,
    PositiveInt,
    ProhibitReactionEffectSchema,
    RollModifierEffectSchema,
    SelfTargetSchema,
    SizeRequirementSchema,
    SpeedMultiplierEffectSchema,
    TimedDurationSchema,
    TurnEconomyRestrictionEffectSchema,
)
from .resolutions import OutcomeSchema, ResolutionSchemaModel

__all__ = [
    "Ability",
    "ActionEffectSchema",
    "ActionMechanicsSchemaModel",
    "ActionRequirementSchema",
    "ActionTargetSchema",
    "AreaTargetSchema",
    "ConditionEffectSchema",
    "ConditionRequirementSchema",
    "ControlEffectSchema",
    "CreatureTargetSchema",
    "CreatureTypeRequirementSchema",
    "DamageEffectSchema",
    "EffectDurationSchema",
    "ForcedMovementEffectSchema",
    "GainMemoriesEffectSchema",
    "NonNegativeInt",
    "NotAffectedRequirementSchema",
    "OutcomeSchema",
    "PositiveInt",
    "ProhibitReactionEffectSchema",
    "RollModifierEffectSchema",
    "ResolutionSchemaModel",
    "SelfTargetSchema",
    "SizeRequirementSchema",
    "SpeedMultiplierEffectSchema",
    "TimedDurationSchema",
    "TurnEconomyRestrictionEffectSchema",
]
