"""Compatibility facade for capability value models.

New code should normally import these models from :mod:`domain.capabilities`.
The implementation is organized by responsibility in sibling modules.
"""

from .effects import (
    ArmorClassModifierEffect,
    AttackHitRequirement,
    AttackRollModeRequirement,
    CapabilityEffect,
    ConditionEffect,
    ConditionImmunityEffect,
    ConditionSaveAdvantageEffect,
    ControlEffect,
    DamageEffect,
    DamageImmunityEffect,
    DamageReductionEffect,
    DamageResistanceEffect,
    EffectDuration,
    ForcedMovementEffect,
    GainMemoriesEffect,
    HealingEffect,
    HitPointMaximumModifierEffect,
    ProhibitReactionsEffect,
    RemoveEffect,
    RollModifierEffect,
    SenseEffect,
    SpeedModifierEffect,
    SpeedMultiplierEffect,
    TemporaryHitPointsEffect,
    TurnEconomyRestrictionEffect,
)
from .outcomes import OutcomeStage, RepeatSave
from .requirements import (
    CapabilityRequirement,
    ConditionImmunityRequirement,
    ConditionRequirement,
    CreatureTraitRequirement,
    CreatureTypeRequirement,
    NotAffectedRequirement,
    RelationshipRequirement,
    SizeRequirement,
)
from .targeting import CapabilityTarget, TargetCount

__all__ = [
    "ArmorClassModifierEffect",
    "AttackHitRequirement",
    "AttackRollModeRequirement",
    "CapabilityEffect",
    "CapabilityRequirement",
    "CapabilityTarget",
    "ConditionEffect",
    "ConditionImmunityEffect",
    "ConditionImmunityRequirement",
    "ConditionRequirement",
    "ConditionSaveAdvantageEffect",
    "ControlEffect",
    "CreatureTraitRequirement",
    "CreatureTypeRequirement",
    "DamageEffect",
    "DamageImmunityEffect",
    "DamageReductionEffect",
    "DamageResistanceEffect",
    "EffectDuration",
    "ForcedMovementEffect",
    "GainMemoriesEffect",
    "HealingEffect",
    "HitPointMaximumModifierEffect",
    "NotAffectedRequirement",
    "OutcomeStage",
    "ProhibitReactionsEffect",
    "RelationshipRequirement",
    "RemoveEffect",
    "RepeatSave",
    "RollModifierEffect",
    "SenseEffect",
    "SizeRequirement",
    "SpeedModifierEffect",
    "SpeedMultiplierEffect",
    "TargetCount",
    "TemporaryHitPointsEffect",
    "TurnEconomyRestrictionEffect",
]
